server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chess_users
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.puzzlegenerator.chess.user_service.kafka"

jwt:
  secret: ${JWT_SECRET:chess-puzzle-platform-secret-key-min-256-bits-long-enough}
  expiration: 3600000
  refresh-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info
